name: Leaper
main: com.sgtcaze.Leaper.Leaper
version: 4.0
authors: [sgtcaze, _Shevchik_]
website: http://sgtcaze.com
commands:
    leaper:
        description: Reload command for Leaper
        usage: /leaper reload - reload configuration